---
# ------------------------------------------------------------------------------------
# -- Docs: https://github.com/imamcs19/edubig-spark-standalone-cluster-and-support-streamlit-port-on-docker --
# -- Additional: PySpark - Smart Big Data App feat Laravel et al
# ------------------------------------------------------------------------------------
version: '3'
services:
#PHP Service
app:
build:
context: .
dockerfile: Dockerfile
image: php_service
container_name: app
restart: unless-stopped
tty: true
environment:
SERVICE_NAME: app
SERVICE_TAGS: dev
working_dir: /var/www
volumes:
- ./:/var/www
- ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
networks:
- app-network

#Nginx Service
webserver:
image: nginx:alpine
container_name: webserver
restart: unless-stopped
tty: true
ports:
- "88:80"
- "443:443"
volumes:
- ./:/var/www
- ./nginx/conf.d/:/etc/nginx/conf.d/
networks:
- app-network

#MySQL Service
db:
image: 
mysqlcontainer_name: db
restart: unless-stopped
tty: true
ports:
- "33061:3306"
environment:
MYSQL_DATABASE: laravel
MYSQL_USER: imamcs19
MYSQL_PASSWORD: abcdef1234
MYSQL_ROOT_PASSWORD: abcdef1234
SERVICE_TAGS: dev
SERVICE_NAME: mysql
networks:
- app-network

#PHPMyAdmin Service
phpmyadmin:
container_name: phpmyadmin
image: phpmyadmin/phpmyadmin
ports:- "7000:80"
links:- db:db
environment:
MYSQL_USER: imamcs19
MYSQL_PASSWORD: abcdef1234
MYSQL_ROOT_PASSWORD: abcdef1234
UPLOAD_LIMIT: 3000000000
networks:
- app-network

#Docker Networks
networks:
app-network:
driver: bridge

#Volumes
volumes:
lbdata:
driver: local