% draft koding Naive Bayes 9 April 2013
% Oleh: Imam Cholissodin
% Fakultas Ilmu Komputer (Filkom) UB

clc;
close all;
clear all;

xpuyuh=[7.8	9.0;...
8.0	9.3;...
8.3	9.1;...
8.0	9.1;...
7.8	9.4]
    
xbebek=[12.5	15.3;...
13.9	15.6;...
13.4	16.3;...
12.1	15.6;...
12.1	15.7]

m_xpuyuh=mean(xpuyuh)
m_xbebek=mean(xbebek) 
m_global=mean([xpuyuh;xbebek])

var_xpuyuh=var(xpuyuh)
var_xbebek=var(xbebek)

% data yang diuji
xtest=[12.2 9.2]

% Menghitung Probabilitas Prior
ppuyuh=size(xpuyuh,1)/(size(xpuyuh,1)+size(xbebek,1))
pbebek=size(xbebek,1)/(size(xpuyuh,1)+size(xbebek,1))

% Menghitung Probabilitas Likelihood dari fitur RBGD
P_Likelihood_kh_given_puyuh=...
    (1/sqrt(2*(22/7)*var_xpuyuh(1)))...
    *exp(-1*(((xtest(1)-m_xpuyuh(1))^2)/(2*var_xpuyuh(1))))
P_Likelihood_kv_given_puyuh=...
    (1/sqrt(2*(22/7)*var_xpuyuh(2)))...
    *exp(-1*(((xtest(2)-m_xpuyuh(2))^2)/(2*var_xpuyuh(2))))

P_Likelihood_kh_given_bebek=...
    (1/sqrt(2*(22/7)*var_xbebek(1)))...
    *exp(-1*(((xtest(1)-m_xbebek(1))^2)/(2*var_xbebek(1))))
P_Likelihood_kv_given_bebek=...
    (1/sqrt(2*(22/7)*var_xbebek(2)))...
    *exp(-1*(((xtest(2)-m_xbebek(2))^2)/(2*var_xbebek(2))))

p_kelas_puyuh_given_x=P_Likelihood_kh_given_puyuh*...
    P_Likelihood_kv_given_puyuh*ppuyuh/(P_Likelihood_kh_given_puyuh*...
    P_Likelihood_kv_given_puyuh*ppuyuh + P_Likelihood_kh_given_bebek*...
    P_Likelihood_kv_given_bebek*pbebek)

p_kelas_bebek_given_x=P_Likelihood_kh_given_bebek*...
    P_Likelihood_kv_given_bebek*pbebek/(P_Likelihood_kh_given_puyuh*...
    P_Likelihood_kv_given_puyuh*ppuyuh + P_Likelihood_kh_given_bebek*...
    P_Likelihood_kv_given_bebek*pbebek)

disp('')    
disp(strcat('Probabilitas Evidence atau P(X) =',num2str(P_Likelihood_kh_given_puyuh*...
    P_Likelihood_kv_given_puyuh*ppuyuh + P_Likelihood_kh_given_bebek*...
    P_Likelihood_kv_given_bebek*pbebek)))

if(p_kelas_puyuh_given_x>p_kelas_bebek_given_x)
    disp(strcat('Jadi X = { KH =',{' '},num2str(xtest(1)),' dan KV =',{' '},num2str(xtest(2)),' } Masuk ke Kelas Puyuh'))
else
    disp(strcat('Jadi X = { KH =',{' '},num2str(xtest(1)),' dan KV =',{' '},num2str(xtest(2)),' } Masuk ke Kelas Bebek'))
end
